language: go

sudo: false

go:
  - 1.x

notifications:
  email: false

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_script:
  - echo $PATH
  - echo $GOPATH
  - go version
  - go env
  - go get -v -t ./src/...
  - go get github.com/mattn/goveralls

script:
  - go test -timeout 1h -covermode=count -coverprofile=coverage.out ./src/cli ./src/models ./src/parser ./src/utils
  - goveralls -coverprofile=coverage.out -service travis-ci
